#!name = Keep净化
#!author = 怎么肥事[https://github.com/Moli-X/Tool/blob/X/Loon/Readme.md]
#!update = 2026-4-14

# Keep分流
host, hc-ssp.sm.cn, reject
host, httpdns.calorietech.com, reject

// 未读消息 & 广告 & 搜索热词
^https:\/\/api\.gotokeep\.com\/messenger\/v\d\/conversations\/unread url reject-dict
^https:\/\/kad\.gotokeep\.com\/op-engine-webapp\/v\d\/ad url reject-dict
^https:\/\/api\.gotokeep\.com\/op-engine-webapp\/v\d\/ad\/preload url reject-dict
^https:\/\/api\.gotokeep\.com\/search\/v\d\/hotHashtag\/list url reject-dict
^https:\/\/api\.gotokeep\.com\/search\/v\d\/hotCourse\/list url reject-dict
^https:\/\/api\.gotokeep\.com\/search\/v\d\/hotword\/list url reject-dict
^https:\/\/api\.gotokeep\.com\/search\/v\d\/default\/keyword\/list url reject-dict

// 个人页 - 移除会员信息 & 多余标签组(订单与钱包/我的团队/帮助中心)
^https:\/\/api\.gotokeep\.com\/athena\/v\d\/people\/my url jsonjq-response-body 'del(.data.memberInfo) | .data.groupTags |= map(select(.tags | all(.name != "订单与钱包" and .name != "我的团队" and .name != "帮助中心")))'

// 基础配置 - 课程Tab移除直播/会员，底部栏移除商城/课程/今日
^https:\/\/api\.gotokeep\.com\/config\/v\d\/basic url jsonjq-response-body '.data.coursePageConfigs.courseTabs |= map(select(.name != "直播" and .name != "会员")) | .data.bottomBarControl.tabs |= map(select(.name != "商城" and .name != "课程" and .name != "今日"))'


hostname = kad.gotokeep.com, 42.187.199.248, api.gotokeep.com
